### ISSUE TITLE
Que los inversionistas valuen mi compañía en miles de millones de dolares

### ISSUE THREAD

**Issue by Sparragus** [birgensita/plis#4]
...y que el inversionista principal compre 49% de la compañía

plis 🙏

**Comment by Sparragus** [comment]
![image](https://cloud.githubusercontent.com/assets/80982/23633828/e0c8bcfe-028c-11e7-9ba2-9dd1a0490a49.png)

**Comment by Sparragus** [comment]
...y que yo sea el que recibe el dinero y luego me desaparezca.

**Comment by Sparragus** [comment]
![image](https://cloud.githubusercontent.com/assets/80982/23633873/11d3da2c-028d-11e7-947f-b2aaf4ee93cd.png)

**Comment by birgencitamx** [comment]
@Sparragus No te lo recomiendo, m'ijo, que el evangelio habla claro sobre las plagas que le caen a los emprendeduristas escurridizos— de entrada se le llenen sus javascripts con [signos de interrogación griegos](http://stackoverflow.com/a/26965332) _(San StackOverflow 26965332, 1)_.

Creo que encontrarás buenos consejos en las [Escrituras de Basecamp](https://37signals.com/rework) para atender a tus plegarias, y ps recuerda que _la señora_ trabaja de maneras misteriosas.

**Comment by Sparragus** [comment]
:pray: 📿
