### ISSUE TITLE
Que ya no se caiga S3, porfis 🙏🏻

### ISSUE THREAD

**Issue by ZuraGuerra** [birgensita/plis#5]

**Comment by birgencitamx** [comment]
M'jita @ZuraGuerra, rezarle a la Birgensita es una cosa de fé; rezarle a la "nube" es esperar milagros y pos así ¿cómo? Haciendo lo que hacemos, no queda de otra más que [apechugar](http://rclone.org), practicar el culto a [varias deidades](https://arstechnica.com/information-technology/2012/11/how-team-obamas-tech-efficiency-left-romney-it-in-dust/), y tener [datos](http://newrelic.com) para [enterarte](https://www.pagerduty.com) y [debuggear](https://www.datadoghq.com) como el monstruo volador de espaguetti manda.
